name: uikit_flutter
description: Themes manager, loader manager and advanced widgets for Flutter projects.
version: 0.0.2+1
homepage: "https://github.com/mobilesoftcode/uikit_flutter"
issue_tracker: "https://github.com/mobilesoftcode/uikit_flutter"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/
  